#!/bin/bash
#
# build.sh
# - generates the object files for longc
#	- generally used in conjunction with ubdate lib

FLAGS="-g -Wall -pedantic -std=c11 -c"
CC="gcc"

# lang
cp -v src/lang.h bin/lang.h

# stack
cp -v src/stack.h bin/stack.h
$CC $FLAGS src/stack.c -o bin/stack.o

# string
cp -v src/string.h bin/string.h
$CC $FLAGS src/string.c -o bin/string.o

# compile to library
ar rcs bin/liblongc.a \
	bin/stack.o \
	bin/string.o
