#!/bin/bash
#
# - script for building using gcc
# - also has debugging options

cmpl_out="test-bytearray"
OBJ="obj/obj"
BYTE="obj/byte/byte"
LIST="obj/list/list"
NODE="obj/list/node"
DLIST="obj/list/dlist/dlist"
NLIST="obj/list/nlist/nlist"
STACK="obj/list/stack/stack"

gcc "implementation.c" \
  "$OBJ.h" "$OBJ.c" \
  "$BYTE.h" "$BYTE.c" \
  "$NODE.h" "$NODE.c" \
  "$LIST.h" \
  "$STACK.h" "$STACK.c" \
  "print/printby.h" \
  -o "$cmpl_out"

if [ "$1" = "-fs" ] || [ "$1" = "--find-segfault" ] ;
  then
  valgrind --leak-check=full "./$cmpl_out"
  #echo "run" | gbd "./$cmpl_out"
fi
