#include <stdbool.h>
#include "returnable.h"
#include "comparable.h"
#include "lctypes.h"

RETURNABLE_TRAIT_C_(bool)
RETURNABLE_TRAIT_C_(char)
RETURNABLE_TRAIT_C_(i8)
RETURNABLE_TRAIT_C_(u8)
RETURNABLE_TRAIT_C_(i16)
RETURNABLE_TRAIT_C_(u16)
RETURNABLE_TRAIT_C_(i32)
RETURNABLE_TRAIT_C_(u32)
RETURNABLE_TRAIT_C_(f32)
RETURNABLE_TRAIT_C_(i64)
RETURNABLE_TRAIT_C_(u64)
RETURNABLE_TRAIT_C_(f64)

COMPARABLE_TRAIT_C_(bool)
COMPARABLE_TRAIT_C_(char)
COMPARABLE_TRAIT_C_(i8)
COMPARABLE_TRAIT_C_(u8)
COMPARABLE_TRAIT_C_(i16)
COMPARABLE_TRAIT_C_(u16)
COMPARABLE_TRAIT_C_(i32)
COMPARABLE_TRAIT_C_(u32)
COMPARABLE_TRAIT_C_(f32)
COMPARABLE_TRAIT_C_(i64)
COMPARABLE_TRAIT_C_(u64)
COMPARABLE_TRAIT_C_(f64)

RETURNABLE_TRAIT_C_(Ref)
COMPARABLE_TRAIT_C_(Ref)
