#ifndef _PRIMITIVE_H_
#define _PRIMITIVE_H_

#include <longc/lang.h>
#include <longc/comparable.h>

enum PRIMITIVE_APPROX_FLAGS {
  BY_BITS,
  BY_DECIMAL,
  BY_PERCENT,
};

TRAIT( COMPARABLE, u8 )
TRAIT( COMPARABLE, i8 )
TRAIT( COMPARABLE, u16)
TRAIT( COMPARABLE, i16)
TRAIT( COMPARABLE, u32)
TRAIT( COMPARABLE, i32)
TRAIT( COMPARABLE, f32)
TRAIT( COMPARABLE, u64)
TRAIT( COMPARABLE, i64)
TRAIT( COMPARABLE, f64)

#endif
